# Generated by Django 4.1 on 2024-07-10 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cateory_name",
                    models.CharField(
                        choices=[
                            ("LOCAL FOOD", "Local Dishes"),
                            ("CONTINENTAL FOOD", "Continental Dishes"),
                            ("OTHERS", "Others"),
                        ],
                        default="Local Dishes",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu",
                        to="food_vendor.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, unique=True)),
                ("available", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="vendor/menu/items/"
                    ),
                ),
                (
                    "menu_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="food_vendor.menucategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuItemPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("REGULAR", "Regular"),
                            ("MEDIUM", "Medium"),
                            ("LARGE", "Large"),
                            ("EXTRA_LARGE", "Extra Large"),
                        ],
                        default="Normal",
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="food_vendor.menuitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("menu_item", "size")},
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_name", models.CharField(max_length=150, unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="vendor/logos/"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash on Delivery"),
                            ("ONLINE", "Online Payment"),
                            ("BOTH", "Both"),
                        ],
                        default="Both",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="food_vendor.menuitem",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="food_vendor.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuItemPriceDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="food_vendor.menuitemprice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menuitem",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="food_vendor.restaurant",
            ),
        ),
        migrations.CreateModel(
            name="Extraitem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=155, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "image",
                    models.ImageField(unique=True, upload_to="vendor/menu/extra_items"),
                ),
                (
                    "menu_item",
                    models.ManyToManyField(
                        blank=True,
                        related_name="extra_items",
                        to="food_vendor.menuitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="food_vendor.restaurant",
            ),
        ),
    ]
