# Generated by Django 4.1 on 2024-07-10 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("item_description", models.TextField()),
                ("item_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("delivery_date", models.DateField()),
                ("special_instructions", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("tracking_number", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrackDeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=155,
                    ),
                ),
                ("location_updates", models.JSONField(default=list)),
                ("timespand", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trackings",
                        to="item_delivery.deliveryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SenderDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_name", models.CharField(max_length=255)),
                ("sender_address", models.TextField()),
                ("sender_city", models.CharField(max_length=100)),
                ("sender_state", models.CharField(max_length=100)),
                ("sender_postal_code", models.CharField(max_length=20)),
                ("sender_phone_number", models.CharField(max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senders",
                        to="item_delivery.deliveryitem",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiverDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_address", models.TextField()),
                ("recipient_city", models.CharField(max_length=100)),
                ("recipient_state", models.CharField(max_length=100)),
                ("recipient_postal_code", models.CharField(max_length=20)),
                ("recipient_phone_number", models.CharField(max_length=20)),
                ("email_address", models.EmailField(max_length=254)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivers",
                        to="item_delivery.deliveryitem",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivers",
                        to="item_delivery.senderdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryItemReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_reviews",
                        to="item_delivery.deliveryitem",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_reviews",
                        to="main.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Item Review",
                "verbose_name_plural": "Delivery Item Reviews",
            },
        ),
        migrations.CreateModel(
            name="CancelDeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cancellation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reason", models.TextField(max_length=500)),
                (
                    "delivery_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancel_deliveries",
                        to="item_delivery.deliveryitem",
                    ),
                ),
            ],
        ),
    ]
