# Generated by Django 5.0.7 on 2024-07-16 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_delivery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryitem",
            old_name="item_weight",
            new_name="weight",
        ),
        migrations.RenameField(
            model_name="receiverdetails",
            old_name="recipient_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="receiverdetails",
            old_name="recipient_city",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="receiverdetails",
            old_name="recipient_state",
            new_name="landmark",
        ),
        migrations.RenameField(
            model_name="receiverdetails",
            old_name="recipient_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="receiverdetails",
            old_name="recipient_phone_number",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="receiverdetails",
            old_name="recipient_postal_code",
            new_name="postal_code",
        ),
        migrations.RenameField(
            model_name="senderdetails",
            old_name="sender_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="senderdetails",
            old_name="sender_city",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="senderdetails",
            old_name="sender_phone_number",
            new_name="postal_code",
        ),
        migrations.RenameField(
            model_name="senderdetails",
            old_name="sender_state",
            new_name="region",
        ),
        migrations.RemoveField(
            model_name="senderdetails",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="senderdetails",
            name="sender_name",
        ),
        migrations.RemoveField(
            model_name="senderdetails",
            name="sender_postal_code",
        ),
        migrations.AlterField(
            model_name="deliveryitem",
            name="tracking_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name="DeliveryItemHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("additional_info", models.TextField(blank=True, null=True)),
                (
                    "delivery_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item_delivery.deliveryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLoction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longtitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
